name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main   # Trigger CI/CD when you push to the 'main' branch
  pull_request:
    branches:
      - main   # Trigger on PR to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'latest'

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test

    - name: Build APK
      run: flutter build apk --release

    - name: Upload to Firebase App Distribution
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Store Firebase token in GitHub Secrets
      run: |
        firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
          --app 1:1088798552262:android:f5debb2b4a2e464e8967c7 \
          --groups "testers" \
          --token "$FIREBASE_TOKEN"
