name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main   # Runs CI/CD when pushing to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'latest'

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze project source
      run: flutter analyze

    - name: Run tests
      run: flutter test

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK as Artifact (Optional)
      uses: actions/upload-artifact@v2  # Adjusted to use v2
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Upload to Firebase App Distribution
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > firebase-service-account.json
        firebase use --add hqarena-fa4c8
        firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
          --app 1:1088798552262:android:f5debb2b4a2e464e8967c7 \
          --groups "testers"
