name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main   # Runs CI/CD when pushing to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.0'

    - name: Verify Dart SDK version
      run: flutter --version

    - name: Clear Pub cache
      run: flutter pub cache repair  

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze project source
      run: flutter analyze

    - name: Authenticate Firebase CLI
      run: |
        echo "$FIREBASE_CREDENTIALS" > firebase_credentials.json
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > firebase-service-account.json
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }} 
        FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

    - name: Run tests
      run: flutter test || echo "Tests failed but continuing deployment."

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK as Artifact (Optional)
      uses: actions/upload-artifact@v4 
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase login --token "$FIREBASE_TOKEN"

    - name: Upload to Firebase App Distribution
      run: |
        firebase use --add hqarena-fa4c8
        firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
          --app 1:1088798552262:android:f5debb2b4a2e464e8967c7 \
          --groups "testers"
